# Generated by Django 2.2.16 on 2021-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=500, null=True)),
                ('pin', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('id_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
