# Generated by Django 2.2.10 on 2021-07-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210708_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client_details',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client_details',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
