# Generated by Django 2.2.10 on 2021-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210715_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
