# Generated by Django 2.2.10 on 2021-07-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210715_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/pics'),
        ),
    ]
