# Generated by Django 2.2.10 on 2021-08-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_district_taluk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='is_banking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='is_exp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='is_smartphone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
