# Generated by Django 2.2.10 on 2021-08-17 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210816_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
