# Generated by Django 2.2.10 on 2021-08-17 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_client_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_details',
            name='date',
        ),
        migrations.AddField(
            model_name='client_details',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
