# Generated by Django 2.2.10 on 2022-02-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210817_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client_details',
        ),
        migrations.RemoveField(
            model_name='taluk',
            name='district',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Taluk',
        ),
    ]
